### ISSUE TITLE
URLs broken because `list_item` doesn't pass URL

### ISSUE THREAD

**Issue by fj** [fj/jxf-dot-me#3]
As of [this commit](https://github.com/fj/jxf-dot-me/commit/7f9a70e5c652a8ea5a3e1825013a8c46bb1e905e), posts and events get generated with blank URLs and titles on the homepage and don't go anywhere.

I assume that's because of [this comment](https://github.com/fj/jxf-dot-me/commit/7f9a70e5c652a8ea5a3e1825013a8c46bb1e905e#commitcomment-9531615).

**Comment by fj** [comment]
Fixed in edf6dc5.

**Comment by johno** [comment]
Nice work, :blush: .
